/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.tads.pi3.projetox.gerenprod.view;

/**
 *
 * @author victor.ganjos
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_MainBackground = new javax.swing.JPanel();
        pnl_TableBackground = new javax.swing.JPanel();
        scp_TableScrollPanel = new javax.swing.JScrollPane();
        tbl_Tabela = new javax.swing.JTable();
        pnl_TitleBackground = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        pnl_FormBackground = new javax.swing.JPanel();
        lbl_Quantidade = new javax.swing.JLabel();
        txt_Quantidade = new javax.swing.JTextField();
        txt_Descricao = new javax.swing.JTextField();
        txt_NomeProduto = new javax.swing.JTextField();
        txt_PrecoCompra = new javax.swing.JTextField();
        lbl_Descricao = new javax.swing.JLabel();
        lbl_PrecoCompra = new javax.swing.JLabel();
        lbl_Status = new javax.swing.JLabel();
        ckb_Ativo = new javax.swing.JCheckBox();
        lbl_SubTitle = new javax.swing.JLabel();
        lbl_NomeProduto = new javax.swing.JLabel();
        txt_PrecoVenda = new javax.swing.JTextField();
        btn_Atualizar = new javax.swing.JButton();
        btn_Remover = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        ckb_Categoria = new javax.swing.JComboBox<>();
        lbl_PrecoVenda1 = new javax.swing.JLabel();
        pnl_SearchBackground = new javax.swing.JPanel();
        lbl_SearchTitle = new javax.swing.JLabel();
        lbl_NomeProdutoBusca = new javax.swing.JLabel();
        txt_NomeProdutoBusca = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_MainBackground.setBackground(new java.awt.Color(49, 89, 110));

        pnl_TableBackground.setBackground(new java.awt.Color(247, 247, 247));
        pnl_TableBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scp_TableScrollPanel.setViewportView(tbl_Tabela);

        pnl_TableBackground.add(scp_TableScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 850, 190));

        pnl_TitleBackground.setBackground(new java.awt.Color(248, 250, 251));
        pnl_TitleBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Title.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(51, 51, 51));
        lbl_Title.setText("Livraria Book's Temple");
        pnl_TitleBackground.add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 805, 61));

        pnl_FormBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Quantidade.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_Quantidade.setText("Quantidade:");
        pnl_FormBackground.add(lbl_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        txt_Quantidade.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pnl_FormBackground.add(txt_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, -1));

        txt_Descricao.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pnl_FormBackground.add(txt_Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 420, 70));

        txt_NomeProduto.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        txt_NomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeProdutoActionPerformed(evt);
            }
        });
        pnl_FormBackground.add(txt_NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 370, -1));

        txt_PrecoCompra.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pnl_FormBackground.add(txt_PrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, -1));

        lbl_Descricao.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_Descricao.setText("Descrição:");
        pnl_FormBackground.add(lbl_Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 20));

        lbl_PrecoCompra.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_PrecoCompra.setText("Preço de Compra:");
        pnl_FormBackground.add(lbl_PrecoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 20));

        lbl_Status.setBackground(new java.awt.Color(204, 204, 204));
        lbl_Status.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_Status.setText("Ativo/Inativo?");
        pnl_FormBackground.add(lbl_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, 20));

        ckb_Ativo.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        ckb_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_AtivoActionPerformed(evt);
            }
        });
        pnl_FormBackground.add(ckb_Ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        lbl_SubTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_SubTitle.setText("Preencha os campos abaixo para adicionar um produto.");
        pnl_FormBackground.add(lbl_SubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 20));

        lbl_NomeProduto.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_NomeProduto.setText("Nome do Produto:");
        pnl_FormBackground.add(lbl_NomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        txt_PrecoVenda.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        pnl_FormBackground.add(txt_PrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, -1));

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });
        pnl_FormBackground.add(btn_Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 80, -1));

        btn_Remover.setText("Remover");
        pnl_FormBackground.add(btn_Remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 80, -1));

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });
        pnl_FormBackground.add(btn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 80, -1));

        ckb_Categoria.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ckb_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_FormBackground.add(ckb_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 140, -1));

        lbl_PrecoVenda1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_PrecoVenda1.setText("Preço de Venda:");
        pnl_FormBackground.add(lbl_PrecoVenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 20));

        pnl_SearchBackground.setBackground(new java.awt.Color(255, 255, 255));

        lbl_SearchTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_SearchTitle.setText("Campo de Busca.");

        lbl_NomeProdutoBusca.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        lbl_NomeProdutoBusca.setText("Nome do Produto:");

        txt_NomeProdutoBusca.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_SearchBackgroundLayout = new javax.swing.GroupLayout(pnl_SearchBackground);
        pnl_SearchBackground.setLayout(pnl_SearchBackgroundLayout);
        pnl_SearchBackgroundLayout.setHorizontalGroup(
            pnl_SearchBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SearchBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SearchBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SearchBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_SearchBackgroundLayout.createSequentialGroup()
                        .addGroup(pnl_SearchBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SearchTitle)
                            .addComponent(lbl_NomeProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_NomeProdutoBusca))
                .addContainerGap())
        );
        pnl_SearchBackgroundLayout.setVerticalGroup(
            pnl_SearchBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SearchBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_SearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbl_NomeProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NomeProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_MainBackgroundLayout = new javax.swing.GroupLayout(pnl_MainBackground);
        pnl_MainBackground.setLayout(pnl_MainBackgroundLayout);
        pnl_MainBackgroundLayout.setHorizontalGroup(
            pnl_MainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_TableBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TitleBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_MainBackgroundLayout.createSequentialGroup()
                        .addComponent(pnl_FormBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_SearchBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_MainBackgroundLayout.setVerticalGroup(
            pnl_MainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_TitleBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_MainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_FormBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(pnl_SearchBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_TableBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_MainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_MainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckb_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_AtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_AtivoActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void txt_NomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeProdutoActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Remover;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JCheckBox ckb_Ativo;
    private javax.swing.JComboBox<String> ckb_Categoria;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JLabel lbl_NomeProduto;
    private javax.swing.JLabel lbl_NomeProdutoBusca;
    private javax.swing.JLabel lbl_PrecoCompra;
    private javax.swing.JLabel lbl_PrecoVenda1;
    private javax.swing.JLabel lbl_Quantidade;
    private javax.swing.JLabel lbl_SearchTitle;
    private javax.swing.JLabel lbl_Status;
    private javax.swing.JLabel lbl_SubTitle;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pnl_FormBackground;
    private javax.swing.JPanel pnl_MainBackground;
    private javax.swing.JPanel pnl_SearchBackground;
    private javax.swing.JPanel pnl_TableBackground;
    private javax.swing.JPanel pnl_TitleBackground;
    private javax.swing.JScrollPane scp_TableScrollPanel;
    private javax.swing.JTable tbl_Tabela;
    private javax.swing.JTextField txt_Descricao;
    private javax.swing.JTextField txt_NomeProduto;
    private javax.swing.JTextField txt_NomeProdutoBusca;
    private javax.swing.JTextField txt_PrecoCompra;
    private javax.swing.JTextField txt_PrecoVenda;
    private javax.swing.JTextField txt_Quantidade;
    // End of variables declaration//GEN-END:variables
}
